module.exports = {
    printWidth: 100000,
    tabWidth: 4,
    useTabs: false,
    semi: true,
    quoteProps: 'as-needed',
    bracketSpacing: true,
    trailingComma: 'all',
    jsxBracketSameLine: false,
    jsxSingleQuote: false,
    arrowParens: 'always',
    insertPragma: false,
    requirePragma: false,
    proseWrap: 'never',
    htmlWhitespaceSensitivity: 'strict',
    endOfLine: 'auto',
    rangeStart: 0,
    vueIndentScriptAndStyle: false,
    singleQuote: true,
};
